name = "test"
compatibility_date = "2024-09-23"
main = ".output/server/index.mjs"
assets = { directory = ".output/public/", binding = "ASSETS" }

[vars]
JWT_SECRET = "dev-only-change-in-production"

[[d1_databases]]
binding = "DB"
database_name = "faithguide-bible"
database_id = "081e3299-b96e-4606-b272-056df09dac5c"
